language: r
warnings_are_errors: true
root: true
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
- tlmgr install fancyvrb units
r_packages:
- drat
after_success:
- wget https://raw.githubusercontent.com/statcourses/drat/master/deploy.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
env:
  global:
    secure: SSM6rcNONuXvAfMqc2XnJIuCz0Z7NxKSNOLLIJNXUGqb1s4t5j8GsJIbSbcX8Xhq9OXqg1r51sE8mB1DAy2PF3jUMelwFf7vb80iA65lpWXVCDJ8RSmIbLP5ln10CC7/mf7sWIQxkYV6jxxQmQO1fx+ppSHNaxF1VDSufcs32hqcc59hqjN5j0kHbCdc02FWNTffycy1Hse1hwv23COf1XsxzgWQ78w0XOTffii7pP1YYwEdWmLWeKauOvG4HMbn2EtdTwmusZyVzTvs78w5f5LEnU7Ch5VxZATjAMYeW6iZDGnAtINsciaWUM4CDb955kuHEwSLtQIe02bIkSyvbUHjgiQcbxAQr/h5w88zwOYrr1gbh3oYYCndSzYN6+pbe8ykGj5E7n/dDdQI96A5mXS023SDvNrrSCYQkeXg5fdqZuTwBn/LjMTR54TS1ENB8pp3B7nKypxysg2xHInP8uAxsiIdpevXe57Wn3fBus5uDvUJhSao/SXTgLbalLKUYl/eUNDPHmUWqqaMRRBkRpf0FgO+FS4upiUwShzi4VTrHoX5ZD3QUdh9sQrc+Crv4XYtjMvQufGKRaQODdVbQnbIPchqTZUA411fLuqE5JgGcTlt+Kh59JrQSispWtlvqpFDBBzqhOofsNg7mE4erYQ4dckqrsHYXOPnUWSdHJE=
